/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Pool {
  query(sql: string, params?: Array<any> | null, timeoutMs?: number | null, signal?: AbortSignal | null): Promise<Array<Record<string, any>>>
  begin(isolation?: string | undefined | null): Promise<Transaction>
  status(): PoolStatus
  end(): Promise<void>
}

export declare class Transaction {
  query(sql: string, params?: Array<any> | null, timeoutMs?: number | null, signal?: AbortSignal | null): Promise<Array<Record<string, any>>>
  commit(): Promise<void>
  rollback(): Promise<void>
}

export declare function createPool(options: PoolOptions): Pool

export declare function hello(name: string): string

export interface PoolOptions {
  hosts: Array<string>
  port?: number
  user: string
  password?: string
  database: string
  poolSize?: number
  connectTimeoutMs?: number
  acquireTimeoutMs?: number
  statementTimeoutMs?: number
  validationIntervalMs?: number
  mode?: string
  applicationName?: string
}

export interface PoolStatus {
  maxSize: number
  size: number
  available: number
  inUse: number
  waiting: number
}
